require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostHashtagsController do

  # This should return the minimal set of attributes required to create a valid
  # PostHashtag. As you add validations to PostHashtag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "post_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostHashtagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all post_hashtags as @post_hashtags" do
      post_hashtag = PostHashtag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:post_hashtags).should eq([post_hashtag])
    end
  end

  describe "GET show" do
    it "assigns the requested post_hashtag as @post_hashtag" do
      post_hashtag = PostHashtag.create! valid_attributes
      get :show, {:id => post_hashtag.to_param}, valid_session
      assigns(:post_hashtag).should eq(post_hashtag)
    end
  end

  describe "GET new" do
    it "assigns a new post_hashtag as @post_hashtag" do
      get :new, {}, valid_session
      assigns(:post_hashtag).should be_a_new(PostHashtag)
    end
  end

  describe "GET edit" do
    it "assigns the requested post_hashtag as @post_hashtag" do
      post_hashtag = PostHashtag.create! valid_attributes
      get :edit, {:id => post_hashtag.to_param}, valid_session
      assigns(:post_hashtag).should eq(post_hashtag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PostHashtag" do
        expect {
          post :create, {:post_hashtag => valid_attributes}, valid_session
        }.to change(PostHashtag, :count).by(1)
      end

      it "assigns a newly created post_hashtag as @post_hashtag" do
        post :create, {:post_hashtag => valid_attributes}, valid_session
        assigns(:post_hashtag).should be_a(PostHashtag)
        assigns(:post_hashtag).should be_persisted
      end

      it "redirects to the created post_hashtag" do
        post :create, {:post_hashtag => valid_attributes}, valid_session
        response.should redirect_to(PostHashtag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved post_hashtag as @post_hashtag" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostHashtag.any_instance.stub(:save).and_return(false)
        post :create, {:post_hashtag => { "post_id" => "invalid value" }}, valid_session
        assigns(:post_hashtag).should be_a_new(PostHashtag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostHashtag.any_instance.stub(:save).and_return(false)
        post :create, {:post_hashtag => { "post_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested post_hashtag" do
        post_hashtag = PostHashtag.create! valid_attributes
        # Assuming there are no other post_hashtags in the database, this
        # specifies that the PostHashtag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PostHashtag.any_instance.should_receive(:update_attributes).with({ "post_id" => "1" })
        put :update, {:id => post_hashtag.to_param, :post_hashtag => { "post_id" => "1" }}, valid_session
      end

      it "assigns the requested post_hashtag as @post_hashtag" do
        post_hashtag = PostHashtag.create! valid_attributes
        put :update, {:id => post_hashtag.to_param, :post_hashtag => valid_attributes}, valid_session
        assigns(:post_hashtag).should eq(post_hashtag)
      end

      it "redirects to the post_hashtag" do
        post_hashtag = PostHashtag.create! valid_attributes
        put :update, {:id => post_hashtag.to_param, :post_hashtag => valid_attributes}, valid_session
        response.should redirect_to(post_hashtag)
      end
    end

    describe "with invalid params" do
      it "assigns the post_hashtag as @post_hashtag" do
        post_hashtag = PostHashtag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostHashtag.any_instance.stub(:save).and_return(false)
        put :update, {:id => post_hashtag.to_param, :post_hashtag => { "post_id" => "invalid value" }}, valid_session
        assigns(:post_hashtag).should eq(post_hashtag)
      end

      it "re-renders the 'edit' template" do
        post_hashtag = PostHashtag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostHashtag.any_instance.stub(:save).and_return(false)
        put :update, {:id => post_hashtag.to_param, :post_hashtag => { "post_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested post_hashtag" do
      post_hashtag = PostHashtag.create! valid_attributes
      expect {
        delete :destroy, {:id => post_hashtag.to_param}, valid_session
      }.to change(PostHashtag, :count).by(-1)
    end

    it "redirects to the post_hashtags list" do
      post_hashtag = PostHashtag.create! valid_attributes
      delete :destroy, {:id => post_hashtag.to_param}, valid_session
      response.should redirect_to(post_hashtags_url)
    end
  end

end
