facebook: &facebook
  key: 274790155904059
  secret: aa3dc1b647378b4fdd096234751afc51
  options: {scope: 'email,user_education_history,friends_education_history,user_birthday,friends_birthday'}

defaults: &defaults
  admin_email: tapgyn@gmail.com
  s3: false

development:
  <<: *defaults
  domain: 0.0.0.0:3000
  facebook:
    <<: *facebook

test:
  <<: *defaults
  domain: test.host
  facebook:
    <<: *facebook