facebook: &facebook
  key: 325545057555650
  secret: c60f05f4033eb502365cfffa205b2ca1
  options: {scope: 'email,user_education_history,friends_education_history,user_birthday,friends_birthday'}

defaults: &defaults
  admin_email: chadstachowicz@gmail.com
  s3: false

development:
  <<: *defaults
  domain: 0.0.0.0:5000
  facebook:
    <<: *facebook

test:
  <<: *defaults

production:
 <<: *defaults
 domain: mindsmesh.herokuapp.com
 sendgrid:
   username: cstachowicz
   password: M1ndsM3sh1
 facebook:
   key: 391884850858794
   secret:  3e2ce240f4214646bf11bacd11378ab0
   options: {scope: 'email,user_education_history,friends_education_history,user_birthday,friends_birthday'}
 s3:
   access_key_id: AKIAIKFVJ3EMAIBXELBQ
   secret_access_key: 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