#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

pwd  = File.dirname(File.expand_path(__FILE__))
file = pwd + '/../config/jobs.rb'
r_env = ENV['RAILS_ENV'] || 'development'

Daemons.run_proc(
  "mindsmesh-#{r_env}-stalker-daemon", # name of daemon
  :dir_mode => :normal,
  :dir => File.join(pwd, '../tmp/pids'),
  :backtrace => true,
  :monitor => true,
  :log_output => true,
  :log_dir => File.join(pwd, '../log')
) do
  exec "stalk #{file}"
end