require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntityLmsController do

  # This should return the minimal set of attributes required to create a valid
  # EntityLm. As you add validations to EntityLm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "lms_provider_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EntityLmsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all entity_lms as @entity_lms" do
      entity_lm = EntityLm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:entity_lms).should eq([entity_lm])
    end
  end

  describe "GET show" do
    it "assigns the requested entity_lm as @entity_lm" do
      entity_lm = EntityLm.create! valid_attributes
      get :show, {:id => entity_lm.to_param}, valid_session
      assigns(:entity_lm).should eq(entity_lm)
    end
  end

  describe "GET new" do
    it "assigns a new entity_lm as @entity_lm" do
      get :new, {}, valid_session
      assigns(:entity_lm).should be_a_new(EntityLm)
    end
  end

  describe "GET edit" do
    it "assigns the requested entity_lm as @entity_lm" do
      entity_lm = EntityLm.create! valid_attributes
      get :edit, {:id => entity_lm.to_param}, valid_session
      assigns(:entity_lm).should eq(entity_lm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EntityLm" do
        expect {
          post :create, {:entity_lm => valid_attributes}, valid_session
        }.to change(EntityLm, :count).by(1)
      end

      it "assigns a newly created entity_lm as @entity_lm" do
        post :create, {:entity_lm => valid_attributes}, valid_session
        assigns(:entity_lm).should be_a(EntityLm)
        assigns(:entity_lm).should be_persisted
      end

      it "redirects to the created entity_lm" do
        post :create, {:entity_lm => valid_attributes}, valid_session
        response.should redirect_to(EntityLm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entity_lm as @entity_lm" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntityLm.any_instance.stub(:save).and_return(false)
        post :create, {:entity_lm => { "lms_provider_id" => "invalid value" }}, valid_session
        assigns(:entity_lm).should be_a_new(EntityLm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntityLm.any_instance.stub(:save).and_return(false)
        post :create, {:entity_lm => { "lms_provider_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entity_lm" do
        entity_lm = EntityLm.create! valid_attributes
        # Assuming there are no other entity_lms in the database, this
        # specifies that the EntityLm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EntityLm.any_instance.should_receive(:update_attributes).with({ "lms_provider_id" => "1" })
        put :update, {:id => entity_lm.to_param, :entity_lm => { "lms_provider_id" => "1" }}, valid_session
      end

      it "assigns the requested entity_lm as @entity_lm" do
        entity_lm = EntityLm.create! valid_attributes
        put :update, {:id => entity_lm.to_param, :entity_lm => valid_attributes}, valid_session
        assigns(:entity_lm).should eq(entity_lm)
      end

      it "redirects to the entity_lm" do
        entity_lm = EntityLm.create! valid_attributes
        put :update, {:id => entity_lm.to_param, :entity_lm => valid_attributes}, valid_session
        response.should redirect_to(entity_lm)
      end
    end

    describe "with invalid params" do
      it "assigns the entity_lm as @entity_lm" do
        entity_lm = EntityLm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntityLm.any_instance.stub(:save).and_return(false)
        put :update, {:id => entity_lm.to_param, :entity_lm => { "lms_provider_id" => "invalid value" }}, valid_session
        assigns(:entity_lm).should eq(entity_lm)
      end

      it "re-renders the 'edit' template" do
        entity_lm = EntityLm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntityLm.any_instance.stub(:save).and_return(false)
        put :update, {:id => entity_lm.to_param, :entity_lm => { "lms_provider_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entity_lm" do
      entity_lm = EntityLm.create! valid_attributes
      expect {
        delete :destroy, {:id => entity_lm.to_param}, valid_session
      }.to change(EntityLm, :count).by(-1)
    end

    it "redirects to the entity_lms list" do
      entity_lm = EntityLm.create! valid_attributes
      delete :destroy, {:id => entity_lm.to_param}, valid_session
      response.should redirect_to(entity_lms_url)
    end
  end

end
