require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HashtagsController do

  # This should return the minimal set of attributes required to create a valid
  # Hashtag. As you add validations to Hashtag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "entity_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HashtagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all hashtags as @hashtags" do
      hashtag = Hashtag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hashtags).should eq([hashtag])
    end
  end

  describe "GET show" do
    it "assigns the requested hashtag as @hashtag" do
      hashtag = Hashtag.create! valid_attributes
      get :show, {:id => hashtag.to_param}, valid_session
      assigns(:hashtag).should eq(hashtag)
    end
  end

  describe "GET new" do
    it "assigns a new hashtag as @hashtag" do
      get :new, {}, valid_session
      assigns(:hashtag).should be_a_new(Hashtag)
    end
  end

  describe "GET edit" do
    it "assigns the requested hashtag as @hashtag" do
      hashtag = Hashtag.create! valid_attributes
      get :edit, {:id => hashtag.to_param}, valid_session
      assigns(:hashtag).should eq(hashtag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hashtag" do
        expect {
          post :create, {:hashtag => valid_attributes}, valid_session
        }.to change(Hashtag, :count).by(1)
      end

      it "assigns a newly created hashtag as @hashtag" do
        post :create, {:hashtag => valid_attributes}, valid_session
        assigns(:hashtag).should be_a(Hashtag)
        assigns(:hashtag).should be_persisted
      end

      it "redirects to the created hashtag" do
        post :create, {:hashtag => valid_attributes}, valid_session
        response.should redirect_to(Hashtag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hashtag as @hashtag" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hashtag.any_instance.stub(:save).and_return(false)
        post :create, {:hashtag => { "entity_id" => "invalid value" }}, valid_session
        assigns(:hashtag).should be_a_new(Hashtag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hashtag.any_instance.stub(:save).and_return(false)
        post :create, {:hashtag => { "entity_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hashtag" do
        hashtag = Hashtag.create! valid_attributes
        # Assuming there are no other hashtags in the database, this
        # specifies that the Hashtag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hashtag.any_instance.should_receive(:update_attributes).with({ "entity_id" => "1" })
        put :update, {:id => hashtag.to_param, :hashtag => { "entity_id" => "1" }}, valid_session
      end

      it "assigns the requested hashtag as @hashtag" do
        hashtag = Hashtag.create! valid_attributes
        put :update, {:id => hashtag.to_param, :hashtag => valid_attributes}, valid_session
        assigns(:hashtag).should eq(hashtag)
      end

      it "redirects to the hashtag" do
        hashtag = Hashtag.create! valid_attributes
        put :update, {:id => hashtag.to_param, :hashtag => valid_attributes}, valid_session
        response.should redirect_to(hashtag)
      end
    end

    describe "with invalid params" do
      it "assigns the hashtag as @hashtag" do
        hashtag = Hashtag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hashtag.any_instance.stub(:save).and_return(false)
        put :update, {:id => hashtag.to_param, :hashtag => { "entity_id" => "invalid value" }}, valid_session
        assigns(:hashtag).should eq(hashtag)
      end

      it "re-renders the 'edit' template" do
        hashtag = Hashtag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hashtag.any_instance.stub(:save).and_return(false)
        put :update, {:id => hashtag.to_param, :hashtag => { "entity_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hashtag" do
      hashtag = Hashtag.create! valid_attributes
      expect {
        delete :destroy, {:id => hashtag.to_param}, valid_session
      }.to change(Hashtag, :count).by(-1)
    end

    it "redirects to the hashtags list" do
      hashtag = Hashtag.create! valid_attributes
      delete :destroy, {:id => hashtag.to_param}, valid_session
      response.should redirect_to(hashtags_url)
    end
  end

end
