require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NotificationSettingsTimesController do

  # This should return the minimal set of attributes required to create a valid
  # NotificationSettingsTime. As you add validations to NotificationSettingsTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotificationSettingsTimesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all notification_settings_times as @notification_settings_times" do
      notification_settings_time = NotificationSettingsTime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:notification_settings_times).should eq([notification_settings_time])
    end
  end

  describe "GET show" do
    it "assigns the requested notification_settings_time as @notification_settings_time" do
      notification_settings_time = NotificationSettingsTime.create! valid_attributes
      get :show, {:id => notification_settings_time.to_param}, valid_session
      assigns(:notification_settings_time).should eq(notification_settings_time)
    end
  end

  describe "GET new" do
    it "assigns a new notification_settings_time as @notification_settings_time" do
      get :new, {}, valid_session
      assigns(:notification_settings_time).should be_a_new(NotificationSettingsTime)
    end
  end

  describe "GET edit" do
    it "assigns the requested notification_settings_time as @notification_settings_time" do
      notification_settings_time = NotificationSettingsTime.create! valid_attributes
      get :edit, {:id => notification_settings_time.to_param}, valid_session
      assigns(:notification_settings_time).should eq(notification_settings_time)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NotificationSettingsTime" do
        expect {
          post :create, {:notification_settings_time => valid_attributes}, valid_session
        }.to change(NotificationSettingsTime, :count).by(1)
      end

      it "assigns a newly created notification_settings_time as @notification_settings_time" do
        post :create, {:notification_settings_time => valid_attributes}, valid_session
        assigns(:notification_settings_time).should be_a(NotificationSettingsTime)
        assigns(:notification_settings_time).should be_persisted
      end

      it "redirects to the created notification_settings_time" do
        post :create, {:notification_settings_time => valid_attributes}, valid_session
        response.should redirect_to(NotificationSettingsTime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notification_settings_time as @notification_settings_time" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationSettingsTime.any_instance.stub(:save).and_return(false)
        post :create, {:notification_settings_time => { "description" => "invalid value" }}, valid_session
        assigns(:notification_settings_time).should be_a_new(NotificationSettingsTime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationSettingsTime.any_instance.stub(:save).and_return(false)
        post :create, {:notification_settings_time => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested notification_settings_time" do
        notification_settings_time = NotificationSettingsTime.create! valid_attributes
        # Assuming there are no other notification_settings_times in the database, this
        # specifies that the NotificationSettingsTime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NotificationSettingsTime.any_instance.should_receive(:update_attributes).with({ "description" => "MyString" })
        put :update, {:id => notification_settings_time.to_param, :notification_settings_time => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested notification_settings_time as @notification_settings_time" do
        notification_settings_time = NotificationSettingsTime.create! valid_attributes
        put :update, {:id => notification_settings_time.to_param, :notification_settings_time => valid_attributes}, valid_session
        assigns(:notification_settings_time).should eq(notification_settings_time)
      end

      it "redirects to the notification_settings_time" do
        notification_settings_time = NotificationSettingsTime.create! valid_attributes
        put :update, {:id => notification_settings_time.to_param, :notification_settings_time => valid_attributes}, valid_session
        response.should redirect_to(notification_settings_time)
      end
    end

    describe "with invalid params" do
      it "assigns the notification_settings_time as @notification_settings_time" do
        notification_settings_time = NotificationSettingsTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationSettingsTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification_settings_time.to_param, :notification_settings_time => { "description" => "invalid value" }}, valid_session
        assigns(:notification_settings_time).should eq(notification_settings_time)
      end

      it "re-renders the 'edit' template" do
        notification_settings_time = NotificationSettingsTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationSettingsTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification_settings_time.to_param, :notification_settings_time => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notification_settings_time" do
      notification_settings_time = NotificationSettingsTime.create! valid_attributes
      expect {
        delete :destroy, {:id => notification_settings_time.to_param}, valid_session
      }.to change(NotificationSettingsTime, :count).by(-1)
    end

    it "redirects to the notification_settings_times list" do
      notification_settings_time = NotificationSettingsTime.create! valid_attributes
      delete :destroy, {:id => notification_settings_time.to_param}, valid_session
      response.should redirect_to(notification_settings_times_url)
    end
  end

end
