require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SectionUsersController do

  def valid_attributes
    {section_id: Fabricate(:section).id, user_id: Fabricate(:user).id}
  end

  describe "GET index" do
    it "assigns all section_users as @section_users" do
      section_user = SectionUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:section_users).should eq([section_user])
    end
  end

  describe "GET show" do
    it "assigns the requested section_user as @section_user" do
      section_user = SectionUser.create! valid_attributes
      get :show, {:id => section_user.to_param}, valid_session
      assigns(:section_user).should eq(section_user)
    end
  end

  describe "GET new" do
    it "assigns a new section_user as @section_user" do
      get :new, {}, valid_session
      assigns(:section_user).should be_a_new(SectionUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested section_user as @section_user" do
      section_user = SectionUser.create! valid_attributes
      get :edit, {:id => section_user.to_param}, valid_session
      assigns(:section_user).should eq(section_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SectionUser" do
        expect {
          post :create, {:section_user => valid_attributes}, valid_session
        }.to change(SectionUser, :count).by(1)
      end

      it "assigns a newly created section_user as @section_user" do
        post :create, {:section_user => valid_attributes}, valid_session
        assigns(:section_user).should be_a(SectionUser)
        assigns(:section_user).should be_persisted
      end

      it "redirects to the created section_user" do
        post :create, {:section_user => valid_attributes}, valid_session
        response.should redirect_to(SectionUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved section_user as @section_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        SectionUser.any_instance.stub(:save).and_return(false)
        SectionUser.any_instance.stub(:errors).and_return(:some => ["errors"])
        post :create, {:section_user => {}}, valid_session
        assigns(:section_user).should be_a_new(SectionUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SectionUser.any_instance.stub(:save).and_return(false)
        SectionUser.any_instance.stub(:errors).and_return(:some => ["errors"])
        post :create, {:section_user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested section_user" do
        section_user = SectionUser.create! valid_attributes
        # Assuming there are no other section_users in the database, this
        # specifies that the SectionUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SectionUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => section_user.to_param, :section_user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested section_user as @section_user" do
        section_user = SectionUser.create! valid_attributes
        put :update, {:id => section_user.to_param, :section_user => valid_attributes}, valid_session
        assigns(:section_user).should eq(section_user)
      end

      it "redirects to the section_user" do
        section_user = SectionUser.create! valid_attributes
        put :update, {:id => section_user.to_param, :section_user => valid_attributes}, valid_session
        response.should redirect_to(section_user)
      end
    end

    describe "with invalid params" do
      it "assigns the section_user as @section_user" do
        section_user = SectionUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SectionUser.any_instance.stub(:save).and_return(false)
        SectionUser.any_instance.stub(:errors).and_return(:some => ["errors"])
        put :update, {:id => section_user.to_param, :section_user => {}}, valid_session
        assigns(:section_user).should eq(section_user)
      end

      it "re-renders the 'edit' template" do
        section_user = SectionUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SectionUser.any_instance.stub(:save).and_return(false)
        SectionUser.any_instance.stub(:errors).and_return(:some => ["errors"])
        put :update, {:id => section_user.to_param, :section_user => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested section_user" do
      section_user = SectionUser.create! valid_attributes
      expect {
        delete :destroy, {:id => section_user.to_param}, valid_session
      }.to change(SectionUser, :count).by(-1)
    end

    it "redirects to the section_users list" do
      section_user = SectionUser.create! valid_attributes
      delete :destroy, {:id => section_user.to_param}, valid_session
      response.should redirect_to(section_users_url)
    end
  end

end