require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TopicsController do

  def valid_attributes
    {name: Faker::Name.name, entity_id: Fabricate(:entity).id}
  end

  describe "GET index" do
    it "assigns all topics as @topics" do
      topic = Topic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:topics).should eq([topic])
    end
  end

  describe "GET show" do
    it "assigns the requested topic as @topic" do
      topic = Topic.create! valid_attributes
      get :show, {:id => topic.to_param}, valid_session
      assigns(:topic).should eq(topic)
      assigns(:topic).should be_present
    end
  end

  describe "PUT join" do
    it "current_user joins the @topic" do
      topic = Fabricate(:topic)
      -> do
        put :join, {:id => topic.to_param}, valid_session
      end.should change { TopicUser.count }.by(1)
      assigns(:topic).should eq(topic)
      assigns(:topic_user).should be_a(TopicUser)
    end
  end

  describe "GET new" do
    it "assigns a new topic as @topic" do
      get :new, {}, valid_session
      assigns(:topic).should be_a_new(Topic)
    end
  end

  describe "GET edit" do
    it "assigns the requested topic as @topic" do
      topic = Topic.create! valid_attributes
      get :edit, {:id => topic.to_param}, valid_session
      assigns(:topic).should eq(topic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Topic" do
        expect {
          post :create, {:topic => valid_attributes}, valid_session
        }.to change(Topic, :count).by(1)
      end

      it "assigns a newly created topic as @topic" do
        post :create, {:topic => valid_attributes}, valid_session
        assigns(:topic).should be_a(Topic)
        assigns(:topic).should be_persisted
      end

      it "redirects to the created topic" do
        post :create, {:topic => valid_attributes}, valid_session
        response.should redirect_to(Topic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved topic as @topic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Topic.any_instance.stub(:save).and_return(false)
        Topic.any_instance.stub(:errors).and_return(:some => ["errors"])
        post :create, {:topic => {}}, valid_session
        assigns(:topic).should be_a_new(Topic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Topic.any_instance.stub(:save).and_return(false)
        Topic.any_instance.stub(:errors).and_return(:some => ["errors"])
        post :create, {:topic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested topic" do
        topic = Topic.create! valid_attributes
        # Assuming there are no other topics in the database, this
        # specifies that the Topic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Topic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => topic.to_param, :topic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested topic as @topic" do
        topic = Topic.create! valid_attributes
        put :update, {:id => topic.to_param, :topic => valid_attributes}, valid_session
        assigns(:topic).should eq(topic)
      end

      it "redirects to the topic" do
        topic = Topic.create! valid_attributes
        put :update, {:id => topic.to_param, :topic => valid_attributes}, valid_session
        response.should redirect_to(topic)
      end
    end

    describe "with invalid params" do
      it "assigns the topic as @topic" do
        topic = Topic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Topic.any_instance.stub(:save).and_return(false)
        Topic.any_instance.stub(:errors).and_return(:some => ["errors"])
        put :update, {:id => topic.to_param, :topic => {}}, valid_session
        assigns(:topic).should eq(topic)
      end

      it "re-renders the 'edit' template" do
        topic = Topic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Topic.any_instance.stub(:save).and_return(false)
        Topic.any_instance.stub(:errors).and_return(:some => ["errors"])
        put :update, {:id => topic.to_param, :topic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested topic" do
      topic = Topic.create! valid_attributes
      expect {
        delete :destroy, {:id => topic.to_param}, valid_session
      }.to change(Topic, :count).by(-1)
    end

    it "redirects to the topics list" do
      topic = Topic.create! valid_attributes
      delete :destroy, {:id => topic.to_param}, valid_session
      response.should redirect_to(topics_url)
    end
  end

  describe "GET more_posts" do
  
    before do
      topic_user = Fabricate(:topic_user, user: current_user_master)
      @topic = topic_user.topic
      @posts = []
      3.times do
        #these should be tested in the model
        #these should be tested in the model
        #these should be tested in the model
        @posts << Fabricate(:post, topic: topic_user.topic, user: topic_user.user)
        @posts << Fabricate(:post, user: topic_user.user)
        Fabricate(:post, topic: topic_user.topic)
        Fabricate(:post)
      end
    end
    describe "empty set" do
      it "renders template" do
        get :more_posts, {id: Fabricate(:topic).to_param}, valid_session
        response.should render_template("posts/more_posts")#these should be tested in the view
        response.should_not render_template("layouts/application")#these should be tested in the view
      end
      it "renders template" do
        get :more_posts, {id: Fabricate(:topic).to_param}, valid_session
        assigns(:posts).size.should == 0
      end
    end
    describe "with posts" do
      it "validating existing of other posts in the database" do
        Post.count.should == 12
      end
      it "with some posts" do
        get :more_posts, {id: @topic.to_param}, valid_session
        assigns(:posts).size.should == 6
      end
      it "applying before" do
        get :more_posts, {id: @topic.to_param, before: @posts.last.id}, valid_session
        assigns(:posts).size.should == 5
      end
      it "applying limit" do
        get :more_posts, {id: @topic.to_param, limit: 1}, valid_session
        assigns(:posts).size.should == 1
      end
      #it "applying after"
    end
  end

end